### PR TITLE
Release/EX-UI_mc_release_bucket3

### PR DESCRIPTION
**Pull request by RiteshHMCTS**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-4117
https://tools.hmcts.net/jira/browse/EUI-3086
https://tools.hmcts.net/jira/browse/EUI-3552
https://tools.hmcts.net/jira/browse/EUI-4085
https://tools.hmcts.net/jira/browse/EUI-197
https://tools.hmcts.net/jira/browse/EUI-4083
https://tools.hmcts.net/jira/browse/EUI-3950

### Change description ###
Release of the above mentioned tickets

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by udaydenduluri33 — DISMISSED** [review]
I can see WA MVP 2 bugs have been fixed as a part of this PR. LGTM

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by adnanakgun — APPROVED** [review]

**Review by udaydenduluri33 — APPROVED** [review]
I can see WA MVP 2 bugs have been fixed as a part of this PR. LGTM

**Pull request merged**
