### PR TITLE
Making OWN same as EXECUTE

### PR DESCRIPTION
**Pull request by connorpgpmcelroy**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-5046

### Change description ###
Agreement that OWN should give same actions as EXECUTE as they give the same actions to different roles

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

### CODE REVIEW

**Review by udaydenduluri33 — APPROVED** [review]
@connorpgpmcelroy  thanks for making the changes

**Review by johnbenjamin-hmcts — APPROVED** [review]
Approved

**Review by kuda1992 — APPROVED** [review]
Looks good to me 😊

**Review by johnbenjamin-hmcts — APPROVED** [review]
Approved

**Pull request merged**
