### PR TITLE
added a failure callback for auth invalid state

### PR DESCRIPTION
**Pull request by phillip-whitaker-hmcts**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-4584

### Change description ###

Added a auth failure callback capture and log

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by ronaldmansveld — DISMISSED** [review]

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by RiteshHMCTS — DISMISSED** [review]

**Review by RiteshHMCTS — DISMISSED** [review]

**Review by RiteshHMCTS — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Comment by phillip-whitaker-hmcts** [comment]
no longer required

**Pull request closed without merging**
