### PR TITLE
EUI-5810 Reasonable adjustment case flag details

### PR DESCRIPTION
**Pull request by johnbenjamin-hmcts**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-5810

### Change description ###
Manage case flags - Reasonable adjustment - Change to display case flag details

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by tarikdogan-hmcts — APPROVED** [review]

**Review by Daniel-Lam — APPROVED** [review]
@johnbenjamin-hmcts - changes approved

**Review by tarikdogan-hmcts — APPROVED** [review]

**Review by Daniel-Lam — APPROVED** [review]
@johnbenjamin-hmcts - changes approved

**Review by Kartheek-S — APPROVED** [review]

**Review by tarikdogan-hmcts — APPROVED** [review]

**Review by Daniel-Lam — APPROVED** [review]
@johnbenjamin-hmcts - changes approved

**Comment by Daniel-Lam** [comment]
Closing this PR following successful QA testing of EUI-5810.

**Pull request closed without merging**
