### PR TITLE
Feature/cross role assignments

### PR DESCRIPTION
**Pull request by udaydenduluri33**
###  JIRA ### 
https://tools.hmcts.net/jira/browse/EUI-5078

### Change description ###

Integrating Task Roles for a Task Id when re-assign

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by johnbenjamin-hmcts — APPROVED** [review]
Approved

**Review by connorpgpmcelroy — APPROVED** [review]
Code LGTM however should really add tests for new functionality if possible
@connorpgpmcelroy - agree and done the changes now

**Review by kuda1992 — APPROVED** [review]
Approved

**Comment by connorpgpmcelroy** [comment]
> Code LGTM however should really add tests for new functionality if possible @connorpgpmcelroy - agree and done the changes now

Tests have now been written and LGTM

**Pull request merged**
