### PR TITLE
allow static caching of assets

### PR DESCRIPTION
**Pull request by paddybasi**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by Daniel-Lam — APPROVED** [review]
Approved, @paddybasi

**Review by andywilkinshmcts — CHANGES_REQUESTED** [review]
paddy - I think I might only be complaining about the title of the PR, but surely this PR removes cache control headers for static assets, meaning that the effect is to "add caching for static assets" , which kind of is the opposite to the title.

Also how does this interact with the IIS config in web.config which is adding these headers?

**Comment by paddybasi** [comment]
> paddy - I think I might only be complaining about the title of the PR, but surely this PR removes cache control headers for static assets, meaning that the effect is to "add caching for static assets" , which kind of is the opposite to the title.
> 
> Also how does this interact with the IIS config in web.config which is adding these headers?

@andywilkinshmcts yes you're right, changed the title to reflect. The web.config file is actually no longer used as far as I'm aware, that was only necessary when we were using azure webapps; now we've moved to AKS we can/should remove this? @ernestman28 can you confirm please?

**Review by andywilkinshmcts — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by Mo-Lala84 — APPROVED** [review]
lgtm

**Pull request merged**
