### PR TITLE
Work allocation/task list component unit tests

### PR DESCRIPTION
**Pull request by connorpgpmcelroy**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-2845

### Change description ###
Adding unit tests for code coverage and editing existing unit tests for testing variation of event handlers

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by ficklephil — APPROVED** [review]

**Comment by ficklephil** [comment]
Only one comment is to have some consistency around naming ie. you have 'secondTaskId' and also 'button2' within the same function. Apart from that, it looks good!

**Review by paul-graham — APPROVED** [review]
Looks pretty comprehensive to me. 👍

**Review by udaydenduluri33 — APPROVED** [review]
LGTMc

**Comment by connorpgpmcelroy** [comment]
Merging - Jenkins build issues due to functional tests, not the relevant commits in branch

**Pull request merged**
