### PR TITLE
mc-release-6.10.0

### PR DESCRIPTION
**Pull request by RiteshHMCTS**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-6328
https://tools.hmcts.net/jira/browse/EUI-6549
https://tools.hmcts.net/jira/browse/EUI-6746
https://tools.hmcts.net/jira/browse/EUI-6370
https://tools.hmcts.net/jira/browse/EUI-6718

### Change description ###
mc release 6.10.0

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by johnbenjamin-hmcts — DISMISSED** [review]

**Review by tarikdogan-hmcts — APPROVED** [review]

**Review by johnbenjamin-hmcts — DISMISSED** [review]

**Review by tarikdogan-hmcts — DISMISSED** [review]

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by udaydenduluri33 — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by tarikdogan-hmcts — APPROVED** [review]

**Review by tarikdogan-hmcts — CHANGES_REQUESTED** [review]
the branch needs syncing with master before merge

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by tarikdogan-hmcts — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by tarikdogan-hmcts — APPROVED** [review]

**Pull request merged**
