### PR TITLE
EUI-3452: Check your answers page show/hide issue

### PR DESCRIPTION
**Pull request by paul-graham**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3452 ✅ `DONE`

### Change description ###
New version of CCD Case UI Toolkit, which incorporates the fix for EUI-3452.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by paul-graham** [comment]
Kind of superseded by https://github.com/hmcts/rpx-xui-webapp/pull/915, which incorporates this fix too. Will leave this one open for the moment, though.

**Comment by paul-graham** [comment]
Not to be merged yet as it's pointing at a tag of CCD Case UI Toolkit.

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by adnanakgun — APPROVED** [review]

**Review by paulhowes-HMCTS — DISMISSED** [review]
This should fix the y18n prototype pollution security issue and I can see this version of the ccd-case-ui-toolkit has the ngModel changes to remove the console warning in development so happy to approve on both these counts.

**Review by udaydenduluri33 — APPROVED** [review]
LGTMp

**Review by kuda1992 — APPROVED** [review]
looks good

**Review by adnanakgun — APPROVED** [review]

**Pull request merged**
