### PR TITLE
DO NOT MERGE YET: Fix issues associated with move from Http to HttpClient

### PR DESCRIPTION
**Pull request by paul-graham**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3490 🟠 `READY FOR QA`
https://tools.hmcts.net/jira/browse/EUI-3494 ✅ `DONE`
https://tools.hmcts.net/jira/browse/EUI-3495 ✅ `DONE`

### Change description ###
Use version "2.72.9-prerelease-fix-case-submission" of CCD Case UI Toolkit, which addresses an issue with the filter on the Case list not working when the "Any" state is chosen, and issues with case submission.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by adnanakgun — APPROVED** [review]

**Review by paulhowes-HMCTS — APPROVED** [review]
Approved.

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Comment by paul-graham** [comment]
Supersedes https://github.com/hmcts/rpx-xui-webapp/pull/905. If this gets merged first, it can be closed.

**Comment by paul-graham** [comment]
Not to be merged yet as it's pointing at a pre-release version of CCD Case UI Toolkit.

**Comment by paul-graham** [comment]
https://github.com/hmcts/rpx-xui-webapp/pull/927 has already been merged into `master`, which contains all the same changes from the toolkit. Therefore, this PR is now redundant.

**Pull request closed without merging**
