### PR TITLE
Feature Global Search

### PR DESCRIPTION
**Pull request by johnbenjamin-hmcts**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4626
https://tools.hmcts.net/jira/browse/EUI-4396
https://tools.hmcts.net/jira/browse/EUI-4371
https://tools.hmcts.net/jira/browse/EUI-4595
https://tools.hmcts.net/jira/browse/EUI-4733

### Change description ###
All Global Search related changes

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by Daniel-Lam — DISMISSED** [review]
@johnbenjamin-hmcts - approving this combination PR.

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by Mo-Lala84 — COMMENTED** [review]
please resolve conflicts

**Review by Daniel-Lam — DISMISSED** [review]
@johnbenjamin-hmcts - approved, following conflict resolution.

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by connorpgpmcelroy — CHANGES_REQUESTED** [review]
Need src to be removed

**Review by connorpgpmcelroy — APPROVED** [review]

**Pull request merged**
