### PR TITLE
Bump ccd version to allow testing

### PR DESCRIPTION
**Pull request by paulhowes-HMCTS**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3410

### Change description ###
Update the ccd version to point at a pre-release version to allow testing of  the ngModel deprecation amends

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by paul-graham — COMMENTED** [review]
Gonna hold off on approving this until such time as you've put the non-pre-release version in the `package.json`. :)

**Review by udaydenduluri33 — APPROVED** [review]
LGTMp

**Review by paul-graham — DISMISSED** [review]
Now references a released version of CCD Case UI Toolkit. 👍

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Comment by paul-graham** [comment]
Not needed as it'll go out with https://github.com/hmcts/rpx-xui-webapp/pull/985.

**Pull request closed without merging**
