### PR TITLE
bug/EUI-6825-fix

### PR DESCRIPTION
**Pull request by Kartheek-S**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-6825

### Change description ###
Booking UI - Without any booking, judge is able to see the tasks

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

### CODE REVIEW

**Review by DavidJayakumar — APPROVED** [review]
Looks fine

**Review by MateiHMCTS — APPROVED** [review]

**Review by connorpgpmcelroy — CHANGES_REQUESTED** [review]
Please answer my questions before merging

**Comment by udaydenduluri33** [comment]
> Please answer my questions before merging

_Two questions Kartheek - 1) We seem to be coding on the basis now that only judges can make a booking - is that a correct evaluation to make? 2) We are getting locations from role assignment info separately to getting relevant service information. I am not sure it could work but did you check to make sure there was no way the extraction of services and locations could be done collaboratively at the same time?_
On behalf of @connorpgpmcelroy

**Comment by Kartheek-S** [comment]
1) We seem to be coding on the basis now that only judges can make a booking - is that a correct evaluation to make? 
_Yes, it's picked from the application routing_
2) We are getting locations from role assignment info separately to getting relevant service information. I am not sure it could work but did you check to make sure there was no way the extraction of services and locations could be done collaboratively at the same time?
_Fixed and changes committed_  
@connorpgpmcelroy , @udaydenduluri33 FYI

**Review by connorpgpmcelroy — APPROVED** [review]

**Pull request merged**
