### PR TITLE
Work allocation/eui 2899

### PR DESCRIPTION
**Pull request by connorpgpmcelroy**
Branch that includes completion of 2899,2900,2901

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-2899
https://tools.hmcts.net/jira/browse/EUI-2900
https://tools.hmcts.net/jira/browse/EUI-2901

### Change description ###
Added unit tests to url-field.component.spec.ts
Added unit tests to image-field.component.spec.ts
Added last unit test to task-field.component.spec.ts

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

### CODE REVIEW

**Review by paul-graham — CHANGES_REQUESTED** [review]
Should be merged into `feature/workallocation/base` instead of `master`.

**Comment by udaydenduluri33** [comment]
> Should be merged into `feature/workallocation/base` instead of `master`.

@paul-graham This has now been done. Also, fixed few LINT errors. Thanks

**Review by udaydenduluri33 — APPROVED** [review]
LGTMc
Being your first JIRA, Very good job!  Thanks.

**Review by paul-graham — APPROVED** [review]
Yeah, all looks good to me.

**Pull request merged**
