### PR TITLE
Feature/e UI 3425 document secure mode phillip whitaker

### PR DESCRIPTION
**Pull request by phillip-whitaker**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-3425 

### Change description ###

Added feature toggle for document secure mode in the caseEditorConfig

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by adnanakgun — APPROVED** [review]

**Review by andywilkinshmcts — APPROVED** [review]

**Comment by udaydenduluri33** [comment]
@phillip-whitaker  things missing
SERVICES_DOCUMENTS_API_PATH_V2 should be added to values.yaml, values.preview.yaml

Also, you might have to add conditional healthcheck for the new URL. You need to introduce a feature toggle on the node which is a boolean.

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by udaydenduluri33 — COMMENTED** [review]
If services.documents.api is not being used can we remove it?

**Review by udaydenduluri33 — DISMISSED** [review]
Approving it on the basis functionality of v2 working along side with old services.documents.api

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by leepavlouhmcts — APPROVED** [review]

**Review by udaydenduluri33 — APPROVED** [review]
Functionality of the documentsv2 URL

**Review by rayliangatos — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by RiteshHMCTS — APPROVED** [review]
approved

**Pull request merged**
