### PR TITLE
feature/wa-release1-pagination-mock-apis

### PR DESCRIPTION
**Pull request by rayliangatos**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4012
https://tools.hmcts.net/jira/browse/EUI-4023
https://tools.hmcts.net/jira/browse/EUI-4028

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by connorpgpmcelroy — APPROVED** [review]
LGTM

**Review by connorpgpmcelroy — CHANGES_REQUESTED** [review]
Test is failing on build actually so can't approve currently

**Review by connorpgpmcelroy — APPROVED** [review]
Tests pass so looks good to me

**Review by udaydenduluri33 — APPROVED** [review]
LGTMr

**Review by kuda1992 — APPROVED** [review]
look good

**Pull request merged**
