### PR TITLE
EUI-5479: Create Case Flag - Reference Data integration

### PR DESCRIPTION
**Pull request by Daniel-Lam**
### JIRA link (if applicable) ###
[EUI-5479](https://tools.hmcts.net/jira/browse/EUI-5479)

### Change description ###
Add API configuration for accessing Reference Data Common API endpoint, for retrieving list of flag types.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Kartheek-S — DISMISSED** [review]

**Review by johnbenjamin-hmcts — APPROVED** [review]
Approved

**Review by johnbenjamin-hmcts — DISMISSED** [review]
Approved

**Comment by Daniel-Lam** [comment]
Closing PR because there is some problem creating a Preview environment.

**Comment by Daniel-Lam** [comment]
Superseded by PR #1928.

**Pull request closed without merging**
