### PR TITLE
Basic test for probate refund pages.

### PR DESCRIPTION
**Pull request by rtiru-hmcts**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

[EUI-5753](https://tools.hmcts.net/jira/browse/EUI-5753)

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### Console Logs ###
```
Rohiths-Air:rpx-xui-webapp rohithtiru$ TEST_URL=https://manage-case.aat.platform.hmcts.net/  yarn run test:smoke
yarn run v1.22.18
warning ../../../../../package.json: No license field
$ webdriver-manager update --versions.chrome 2.40 && protractor ./test/e2e/config/smoke.conf.js
[19:49:52] I/update - chromedriver: file exists /Users/rohithtiru/workspace/solirius/repos/new/rpx-xui-webapp/node_modules/webdriver-manager/selenium/chromedriver_2.40.zip
[19:49:53] I/update - chromedriver: unzipping chromedriver_2.40.zip
[19:49:53] I/update - chromedriver: setting permissions to 0755 for /Users/rohithtiru/workspace/solirius/repos/new/rpx-xui-webapp/node_modules/webdriver-manager/selenium/chromedriver_2.40
[19:49:53] I/update - chromedriver: chromedriver_2.40 up to date
[19:49:53] I/update - selenium standalone: file exists /Users/rohithtiru/workspace/solirius/repos/new/rpx-xui-webapp/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar
[19:49:53] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
[19:49:53] I/update - geckodriver: file exists /Users/rohithtiru/workspace/solirius/repos/new/rpx-xui-webapp/node_modules/webdriver-manager/selenium/geckodriver-v0.31.0.tar.gz
[19:49:53] I/update - geckodriver: unzipping geckodriver-v0.31.0.tar.gz
[19:49:53] I/update - geckodriver: setting permissions to 0755 for /Users/rohithtiru/workspace/solirius/repos/new/rpx-xui-webapp/node_modules/webdriver-manager/selenium/geckodriver-v0.31.0
[19:49:53] I/update - geckodriver: geckodriver-v0.31.0 up to date
[19:49:55] I/launcher - Running 1 instances of WebDriver
[19:49:55] I/direct - Using ChromeDriver directly...
WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
(node:71457) DeprecationWarning: cucumber: defineSupportCode is deprecated. Please require/import the individual methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:71457) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
@probate @fullfunctional @refunds
Feature: Probate Refunds

  @probate @fullfunctional @refunds @reviewcase
  Scenario: Verify Review Case
    When I navigate to Expert UI Url
    Given I am logged into Expert UI with Probate user details
ONE ATTEMPT:  EUI-1856 issue occured / total logins => 0 / 1
TWO ATTEMPT: EUI-1856 issue occured / total logins => 0 / 1
    Then I should be redirected to EUI dashboard page
[19:50:15] W/element - more than one element found for locator By(css selector, exui-header .hmcts-primary-navigation__item) - the first result will be used
    When I click on Refunds button
    Then Refunds page should be displayed
    When I click Review case
    Then Review case page should be displayed
(node:71457) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

  @probate @fullfunctional @refunds @processrefund
  Scenario: Verify Process Refund
    When I navigate to Expert UI Url
    Given I am logged into Expert UI with Probate user details
ONE ATTEMPT:  EUI-1856 issue occured / total logins => 0 / 2
TWO ATTEMPT: EUI-1856 issue occured / total logins => 0 / 2
    Then I should be redirected to EUI dashboard page
[19:50:48] W/element - more than one element found for locator By(css selector, exui-header .hmcts-primary-navigation__item) - the first result will be used
    When I click on Refunds button
    Then Refunds page should be displayed
    When I click Process refund
    Then Process refund page should be displayed

  @probate @fullfunctional @refunds @reviewrefund
  Scenario: Verify Review Refund
    When I navigate to Expert UI Url
    Given I am logged into Expert UI with Probate user details
ONE ATTEMPT:  EUI-1856 issue occured / total logins => 0 / 3
TWO ATTEMPT: EUI-1856 issue occured / total logins => 0 / 3
    Then I should be redirected to EUI dashboard page
[19:51:38] W/element - more than one element found for locator By(css selector, exui-header .hmcts-primary-navigation__item) - the first result will be used
    When I click on Refunds button
    Then Refunds page should be displayed
    When I click Review refund
    Then Review refund page should be displayed

3 scenarios (3 passed)
21 steps (21 passed)
1m37.223s


=====================================================================================
    Multiple Cucumber HTML report generated in:

    /Users/rohithtiru/workspace/solirius/repos/new/rpx-xui-webapp/reports/tests/smoke/index.html
=====================================================================================

[19:51:44] I/launcher - 0 instance(s) of WebDriver still running
[19:51:44] I/launcher - chrome #01 passed
✨  Done in 113.23s.
```

### CODE REVIEW

**Review by Vamshi-Muniganti — DISMISSED** [review]
looks fine to me

**Review by sreekanthpuligadda — DISMISSED** [review]
LGTM

**Review by Vamshi-Muniganti — APPROVED** [review]
looks ok to me

**Review by sreekanthpuligadda — APPROVED** [review]
LGTM

**Pull request merged**
