### PR TITLE
feature/wa-release1-pagination

### PR DESCRIPTION
**Pull request by rayliangatos**
* feature/wa-release1-pagination-mock-apis

* change path

* fix test

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4013
https://tools.hmcts.net/jira/browse/EUI-4024
https://tools.hmcts.net/jira/browse/EUI-4029
https://tools.hmcts.net/jira/browse/EUI-4031

### Change description ###
Add pagination on WA MVP

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by connorpgpmcelroy — APPROVED** [review]
LGTM

**Review by udaydenduluri33 — DISMISSED** [review]
LGTMr

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by leepavlouhmcts — APPROVED** [review]

**Review by connorpgpmcelroy — APPROVED** [review]

**Review by kuda1992 — APPROVED** [review]
looks good

**Pull request merged**
