### PR TITLE
Semicolons

### PR DESCRIPTION
**Pull request by paul-graham**
### Change description ###
Allow semicolons in the node layer to align it with the Angular layer. It will now warn about missing semicolons.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by ficklephil — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by rayliangatos — APPROVED** [review]
Do you need another PR to add the ; back to every file to make the codes be consistent?

**Comment by paul-graham** [comment]
> Do you need another PR to add the ; back to every file to make the codes be consistent?

If we're going to do that, we will. For now, though, this simply allows them again and warns if they're not in place, which is exactly what we have in the node layer.

**Comment by paul-graham** [comment]
Closed by the bot because it was "stale", but it's still needed.

**Comment by paul-graham** [comment]
Appears to have been merged by some other means.

**Pull request closed without merging**
