### PR TITLE
cve temp fix

### PR DESCRIPTION
**Pull request by ernestman28**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-5579

### Change description ###

CVE temp fix

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by paulhowes-HMCTS — APPROVED** [review]
Yarn audit workaround so approving

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by paulhowes-HMCTS — APPROVED** [review]
CVE workaround - approved

**Pull request merged**
