### PR TITLE
idam id different for oidc/oAuth2

### PR DESCRIPTION
**Pull request by udaydenduluri33**
### Change description ###

Based on the Authentication protocol we use we get a different response of the user object. Our code should work with both the authentication protocols

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by connorpgpmcelroy — APPROVED** [review]
LGTM

**Review by rayliangatos — APPROVED** [review]
Approved but want to ask the difference between id and uid.

**Review by rayliangatos — APPROVED** [review]

**Review by connorpgpmcelroy — APPROVED** [review]
LGTM

**Review by Daniel-Lam — APPROVED** [review]
Changes are approved

**Review by paul-graham — APPROVED** [review]
Wouldn't quite have been how I'd have done it but it'll do fine.

**Pull request merged**
