### PR TITLE
Feature/e UI 3773 add em hrs api proxy

### PR DESCRIPTION
**Pull request by benouaer**
### JIRA link (if applicable) ###
- https://tools.hmcts.net/jira/browse/EUI-3773

### Change description ###
- add proxy configuration for em-hrs-api endpoint

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by udaydenduluri33 — APPROVED** [review]
LGTMm

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by udaydenduluri33 — DISMISSED** [review]
LGTMm

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by leepavlouhmcts — APPROVED** [review]

**Review by udaydenduluri33 — DISMISSED** [review]
LGTMe

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by udaydenduluri33 — APPROVED** [review]
LGTMb

**Review by leepavlouhmcts — APPROVED** [review]

**Review by phillip-whitaker — APPROVED** [review]

**Pull request merged**
