### PR TITLE
MC CVE temp1

### PR DESCRIPTION
**Pull request by sakanam**
### Change description ###
cve supression

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by rayliangatos — COMMENTED** [review]
Is that yarn-audit-known-issue added incorrectly? It already has yarn-audit-known-issues.

**Review by RiteshHMCTS — APPROVED** [review]

**Review by sakanam — COMMENTED** [review]
@rayliangatos Yarn audit-known-issue has been added correctly

**Review by rayliangatos — APPROVED** [review]
thanks for addressing comment, approved.

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Pull request merged**
