### PR TITLE
PR for - Error when user returns to previous page and correctly popul…

### PR DESCRIPTION
**Pull request by kuda1992**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3770

### Change description ###
Error when user returns to previous page and correctly populates a mandatory field

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by paul-graham — CHANGES_REQUESTED** [review]
All fine... but can't approve it until it's pointing at a fully released version of the toolkit. :)

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by paul-graham — APPROVED** [review]
Now pointing at a fully-released version of the CCD Case UI Toolkit. 👍

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Pull request merged**
