### PR TITLE
Fix caseworker parameter issue

### PR DESCRIPTION
**Pull request by connorpgpmcelroy**
Also edit tests

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4707

### Change description ###
Fix issue with task manager when searching all caseworkers by removing search parameter completely in that instance. Searching by unassigned caseworkers and individual caseworkers still available.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

### CODE REVIEW

**Review by udaydenduluri33 — DISMISSED** [review]
@connorpgpmcelroy LGTM

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by udaydenduluri33 — DISMISSED** [review]

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by udaydenduluri33 — APPROVED** [review]

**Review by RiteshHMCTS — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Pull request merged**
