### PR TITLE
Release/6.2.0b

### PR DESCRIPTION
**Pull request by ronaldmansveld**
### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by johnbenjamin-hmcts — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by johnbenjamin-hmcts — APPROVED** [review]

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by johnbenjamin-hmcts — APPROVED** [review]

**Review by leepavlouhmcts — APPROVED** [review]

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by johnbenjamin-hmcts — DISMISSED** [review]

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by johnbenjamin-hmcts — DISMISSED** [review]

**Review by johnbenjamin-hmcts — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by johnbenjamin-hmcts — DISMISSED** [review]

**Review by Mo-Lala84 — DISMISSED** [review]
aapproved

**Review by johnbenjamin-hmcts — DISMISSED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by johnbenjamin-hmcts — APPROVED** [review]

**Pull request merged**
