### PR TITLE
EUI-5650-private-law-production-onboarding

### PR DESCRIPTION
**Pull request by RiteshHMCTS**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-5650

### Change description ###
Private Law Production Onboarding

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by phillip-whitaker-hmcts — APPROVED** [review]
Simple change

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by phillip-whitaker-hmcts — APPROVED** [review]
LGTM

**Pull request merged**
